apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-gateway-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/renukarajappa/fintech-gitops.git
    targetRevision: HEAD
    path: payment-gateway
    helm:
      valueFiles:
        - values/prod.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
